#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# send_data:
#     path: /sendData
#     controller: App\Controller\YourController::sendDataAction
#     methods: [POST]

# gallery:
#     path: /gallery
#     controller: App\Controller\MainController::gallery